"""add phase 2 schema for content processing

Revision ID: 18610ce9ee70
Revises: a41a7b3dc8d6
Create Date: 2026-04-19 12:09:31.200137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18610ce9ee70'
down_revision: Union[str, Sequence[str], None] = 'a41a7b3dc8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
