"""Add missing foreign key indexes

Revision ID: a41a7b3dc8d6
Revises: 98312fe87bd7
Create Date: 2026-04-04 14:58:44.898410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41a7b3dc8d6'
down_revision: Union[str, Sequence[str], None] = '98312fe87bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_artefacts_unit_id'), 'ai_artefacts', ['unit_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_school_id'), 'analytics_events', ['school_id'], unique=False)
    op.create_index(op.f('ix_free_ask_exchanges_session_id'), 'free_ask_exchanges', ['session_id'], unique=False)
    op.create_index(op.f('ix_free_ask_exchanges_unit_id'), 'free_ask_exchanges', ['unit_id'], unique=False)
    op.create_index(op.f('ix_learning_units_note_id'), 'learning_units', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_assignments_note_id'), 'note_assignments', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_assignments_target_id'), 'note_assignments', ['target_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_progress_artefact_id'), 'student_progress', ['artefact_id'], unique=False)
    op.create_index(op.f('ix_student_progress_student_id'), 'student_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_progress_unit_id'), 'student_progress', ['unit_id'], unique=False)
    op.create_index(op.f('ix_voice_interactions_session_id'), 'voice_interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_note_id'), 'voice_sessions', ['note_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_student_id'), 'voice_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_sessions_student_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_note_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_interactions_session_id'), table_name='voice_interactions')
    op.drop_index(op.f('ix_student_progress_unit_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_student_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_artefact_id'), table_name='student_progress')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_note_assignments_target_id'), table_name='note_assignments')
    op.drop_index(op.f('ix_note_assignments_note_id'), table_name='note_assignments')
    op.drop_index(op.f('ix_learning_units_note_id'), table_name='learning_units')
    op.drop_index(op.f('ix_free_ask_exchanges_unit_id'), table_name='free_ask_exchanges')
    op.drop_index(op.f('ix_free_ask_exchanges_session_id'), table_name='free_ask_exchanges')
    op.drop_index(op.f('ix_analytics_events_school_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_ai_artefacts_unit_id'), table_name='ai_artefacts')
    # ### end Alembic commands ###
