"""Add class_id column to lesson_notes table

Revision ID: f5c1d9a2e1b3
Revises: 18610ce9ee70
Create Date: 2026-05-19 06:08:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f5c1d9a2e1b3'
down_revision: Union[str, Sequence[str], None] = '18610ce9ee70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add class_id column to lesson_notes table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add the class_id column
    op.add_column('lesson_notes', sa.Column('class_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Create the foreign key constraint
    op.create_foreign_key('fk_lesson_notes_class_id', 'lesson_notes', 'classes', ['class_id'], ['id'])
    
    # Create index for performance
    op.create_index(op.f('ix_lesson_notes_class_id'), 'lesson_notes', ['class_id'], unique=False)
    
    # Update existing rows to NOT NULL by using a subquery with subject_id relationship
    # This assumes we can get class_id from the class_subjects table
    op.execute("""
        UPDATE lesson_notes 
        SET class_id = cs.class_id 
        FROM class_subjects cs 
        WHERE lesson_notes.subject_id = cs.id AND lesson_notes.class_id IS NULL
    """)
    
    # Now make the column NOT NULL
    op.alter_column('lesson_notes', 'class_id', existing_type=postgresql.UUID(as_uuid=True), nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove class_id column from lesson_notes table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_notes_class_id'), table_name='lesson_notes')
    op.drop_constraint('fk_lesson_notes_class_id', 'lesson_notes', type_='foreignkey')
    op.drop_column('lesson_notes', 'class_id')
    # ### end Alembic commands ###
